# Generated by Django 5.1.15 on 2026-09-12 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoadSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', models.JSONField()),
                ('road_class', models.CharField(max_length=32)),
                ('surface', models.CharField(max_length=32)),
                ('has_bridge', models.BooleanField(default=False)),
                ('from_node', models.CharField(max_length=64)),
                ('to_node', models.CharField(max_length=64)),
                ('length_m', models.FloatField()),
                ('risk_penalty', models.FloatField(default=0)),
            ],
        ),
    ]
