# Generated by Django 5.1.15 on 2026-09-12 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExposureAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('road', 'Road'), ('bridge', 'Bridge'), ('hospital', 'Hospital'), ('school', 'School'), ('village', 'Village'), ('power', 'Power'), ('rail', 'Rail'), ('tourist', 'Tourist')], max_length=16)),
                ('geom', models.JSONField()),
                ('name', models.CharField(max_length=120)),
                ('population', models.PositiveIntegerField(default=0)),
                ('capacity', models.PositiveIntegerField(default=0)),
                ('criticality', models.PositiveSmallIntegerField(default=1)),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exposure_assets', to='geo.region')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exposure_assets', to='geo.slopeunit')),
            ],
        ),
    ]
