# Generated by Django 5.1.15 on 2026-09-12 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=10)),
                ('window_start', models.DateTimeField()),
                ('window_end', models.DateTimeField()),
                ('message', models.TextField()),
                ('drivers', models.JSONField(default=dict)),
                ('recommended_action', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('ack', 'Ack'), ('resolved', 'Resolved')], default='new', max_length=12)),
                ('false_alarm_flag', models.BooleanField(default=False)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='geo.region')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='geo.slopeunit')),
            ],
        ),
    ]
