# Generated by Django 5.1.15 on 2026-09-12 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
                ('rain_mm', models.FloatField(default=0)),
                ('soil_moisture_pred', models.FloatField(default=0)),
                ('source', models.CharField(default='demo', max_length=80)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='geo.slopeunit')),
            ],
        ),
        migrations.CreateModel(
            name='DynamicObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(db_index=True)),
                ('rain_1h_mm', models.FloatField(default=0)),
                ('rain_24h_mm', models.FloatField(default=0)),
                ('rain_72h_mm', models.FloatField(default=0)),
                ('intensity_mm_h', models.FloatField(default=0)),
                ('soil_moisture_pct', models.FloatField(default=0)),
                ('temp_c', models.FloatField(default=0)),
                ('source', models.CharField(default='demo', max_length=80)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='geo.slopeunit')),
            ],
            options={
                'ordering': ['-ts'],
                'indexes': [models.Index(fields=['unit', '-ts'], name='monitoring__unit_id_8ea6f1_idx')],
            },
        ),
    ]
