# Generated by Django 5.1.15 on 2026-09-12 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SusceptibilityScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_version', models.CharField(max_length=64)),
                ('score', models.FloatField()),
                ('probability', models.FloatField()),
                ('shap_values', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='susceptibility_scores', to='geo.slopeunit')),
            ],
        ),
        migrations.CreateModel(
            name='RiskSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(db_index=True)),
                ('static_risk', models.FloatField()),
                ('dynamic_risk', models.FloatField()),
                ('exposure_score', models.FloatField(default=0)),
                ('fused_risk', models.FloatField()),
                ('velocity', models.FloatField(default=0)),
                ('level', models.CharField(choices=[('LOW', 'Low'), ('WATCH', 'Watch'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical')], max_length=10)),
                ('drivers', models.JSONField(default=dict)),
                ('weights', models.JSONField(default=dict)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_snapshots', to='geo.slopeunit')),
            ],
            options={
                'ordering': ['-ts'],
                'indexes': [models.Index(fields=['unit', '-ts'], name='risk_risksn_unit_id_47b14e_idx')],
            },
        ),
    ]
