# Generated by Django 5.1.15 on 2026-09-12 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('static', 'Static'), ('fusion', 'Fusion'), ('anomaly', 'Anomaly')], max_length=16)),
                ('artifact_path', models.CharField(max_length=255)),
                ('metrics', models.JSONField(default=dict)),
                ('trained_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
