# Generated by Django 5.1.15 on 2026-09-12 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('boundary', models.JSONField()),
                ('centroid', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalLandslide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', models.JSONField()),
                ('occurred_on', models.DateField()),
                ('landslide_type', models.CharField(max_length=64)),
                ('severity', models.CharField(blank=True, max_length=32)),
                ('volume_m3', models.FloatField(blank=True, null=True)),
                ('source', models.CharField(max_length=120)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('verified', models.BooleanField(default=False)),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historical_landslides', to='geo.region')),
            ],
        ),
        migrations.CreateModel(
            name='SlopeUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', models.JSONField()),
                ('centroid', models.JSONField()),
                ('area_ha', models.FloatField()),
                ('unit_code', models.CharField(max_length=64, unique=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slope_units', to='geo.region')),
            ],
        ),
        migrations.CreateModel(
            name='StaticFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elevation_m', models.FloatField()),
                ('slope_deg', models.FloatField()),
                ('aspect_deg', models.FloatField(default=0)),
                ('soil_type', models.CharField(max_length=80)),
                ('lithology', models.CharField(max_length=80)),
                ('lulc', models.CharField(max_length=80)),
                ('drainage_density', models.FloatField(default=0)),
                ('fault_distance_m', models.FloatField(default=0)),
                ('hist_landslide_density', models.FloatField(default=0)),
                ('unit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='static_features', to='geo.slopeunit')),
            ],
        ),
        migrations.AddIndex(
            model_name='slopeunit',
            index=models.Index(fields=['region', 'unit_code'], name='geo_slopeun_region__618952_idx'),
        ),
    ]
