import { createContext, useContext, useEffect, useState, type ReactNode } from "react";

export type Language = "en" | "as" | "bn" | "kha" | "brx";

const translations: Record<Language, Record<string, string>> = {
  en: { console: "Command console", map: "Risk map", analytics: "Risk analytics", routes: "Route safety", impact: "Impact analysis", alerts: "Alerts", simulate: "Simulation", live: "LIVE MONITORING", synthetic: "SYNTHETIC FEED", api: "API CONNECTED", synced: "SYNCED JUST NOW", fused: "FUSED RISK", units: "MONITORED UNITS", warnings: "ACTIVE WARNINGS", velocity: "RISK VELOCITY", spatial: "SPATIAL INTELLIGENCE", hazard: "Live hazard field", conditions: "Conditions now", explain: "Why this area is risky", active: "Active alerts", scenario: "Test a rainfall surge" },
  as: { console: "কমান্ড কনছ'ল", map: "বিপদৰ মানচিত্ৰ", analytics: "বিপদ বিশ্লেষণ", routes: "পথৰ সুৰক্ষা", impact: "প্ৰভাৱ বিশ্লেষণ", alerts: "সতৰ্কবাণী", simulate: "অনুকৰণ", live: "লাইভ নিৰীক্ষণ", synthetic: "কৃত্ৰিম তথ্য", api: "API সংযুক্ত", synced: "এতিয়াই সংৰক্ষণ", fused: "সংযুক্ত বিপদ", units: "নিৰীক্ষণাধীন এলেকা", warnings: "সক্ৰিয় সতৰ্কবাণী", velocity: "বিপদৰ গতি", spatial: "স্থানিক তথ্য", hazard: "লাইভ বিপদ ক্ষেত্ৰ", conditions: "বৰ্তমান পৰিস্থিতি", explain: "এই এলেকা কিয় বিপদজনক", active: "সক্ৰিয় সতৰ্কবাণী", scenario: "বৰষুণৰ পৰিৱৰ্তন পৰীক্ষা" },
  bn: { console: "কমান্ড কনসোল", map: "ঝুঁকি মানচিত্র", analytics: "ঝুঁকি বিশ্লেষণ", routes: "পথের নিরাপত্তা", impact: "প্রভাব বিশ্লেষণ", alerts: "সতর্কতা", simulate: "সিমুলেশন", live: "লাইভ পর্যবেক্ষণ", synthetic: "সিন্থেটিক ডেটা", api: "API সংযুক্ত", synced: "এইমাত্র সিঙ্ক হয়েছে", fused: "সমন্বিত ঝুঁকি", units: "পর্যবেক্ষিত এলাকা", warnings: "সক্রিয় সতর্কতা", velocity: "ঝুঁকির গতি", spatial: "স্থানিক তথ্য", hazard: "লাইভ বিপদ ক্ষেত্র", conditions: "বর্তমান অবস্থা", explain: "এই এলাকা ঝুঁকিপূর্ণ কেন", active: "সক্রিয় সতর্কতা", scenario: "বৃষ্টির পরিবর্তন পরীক্ষা" },
  kha: { console: "Ka kamand konsol", map: "Ka map jingma", analytics: "Ka jingbishar jingma", routes: "Ka jingshngain lynti", impact: "Ka jingbishar jingktah", alerts: "Ki jingmaham", simulate: "Ka jingsimul", live: "KA JINGPEIT LIVE", synthetic: "KI DATA BA THAW", api: "API BA PYNMLIEN", synced: "LA SYNC TANG SHEN", fused: "JINGMA BA PYNLANG", units: "KI THAIN BA PEIT", warnings: "KI JINGMAHAM BA TREI", velocity: "KA SPEED JINGMA", spatial: "KI TIP SHAPAT", hazard: "Ka jaka jingma live", conditions: "Ki jinglong mynta", explain: "Balei kane ka jaka ka long jingma", active: "Ki jingmaham ba trei", scenario: "To test ka jingkylla slap" },
  brx: { console: "कमाण्ड कन्सोल", map: "जोखोम मेप", analytics: "जोखोम बिसार", routes: "रुट सेफ्टी", impact: "इम्पेक्ट बिसार", alerts: "सावधान", simulate: "सिमुलेसन", live: "लाइभ मोनिटरिं", synthetic: "सिन्थेटिक डाटा", api: "API जोंखा", synced: "आबो सिंक जादों", fused: "जोखोम फ्युजन", units: "मोनिटर जोंखा", warnings: "सक्रिय सावधान", velocity: "जोखोम स्पिड", spatial: "जायगा बिसार", hazard: "लाइभ जोखोम जायगा", conditions: "दानि हाबा", explain: "बे जायगा मानो जोखोम", active: "सक्रिय सावधान", scenario: "बर्खा सोलायन टेस्ट" },
};

const dashboardTranslations: Record<Language, Record<string, string>> = {
  en: { regionView: "NORTH EASTERN REGION / OPERATIONAL VIEW", evolves: "Risk evolves with the environment. Watch the conditions that change the outcome.", offline: "OFFLINE DEMO MODE", syncing: "SYNCING...", fused: "FUSED RISK", monitored: "MONITORED UNITS", activeSlope: "ACTIVE SLOPE UNITS", activeWarnings: "ACTIVE WARNINGS", pointsHour: "POINTS / HOUR", rapid: "Risk is rapidly increasing across the eastern corridor.", routeSafety: "ROUTE SAFETY", impactPriority: "IMPACT PRIORITY", primaryReview: "Primary corridor under review", easternPriority: "Eastern corridor · Priority 01", routeCopy: "Risk-aware routing is ready to compare the shortest path with a safer alternative.", impactCopy: "Combine hazard probability with population and infrastructure exposure before dispatch.", openRoute: "OPEN ROUTE ANALYSIS", openImpact: "OPEN IMPACT ANALYSIS", spatial: "SPATIAL INTELLIGENCE", hazard: "Live hazard field", temporal: "TEMPORAL SIGNAL", riskVelocity: "Risk velocity", conditions: "Conditions now", rainfall: "Rainfall · 24h", currentAccumulation: "Current accumulation", soilMoisture: "Soil moisture", saturation: "Saturation index", forecastRisk: "Forecast risk", nextHours: "Next 6 hours", forecastWindow: "FORECAST WINDOW", peak: "Peak intensity expected in 03:40 hrs", explainTitle: "Why this area is risky", explainCopy: "The fusion engine is weighing these factors most heavily right now.", activeAlerts: "Active alerts", whatIf: "WHAT-IF SIMULATION", surge: "Test a rainfall surge", rainfallChange: "rainfall change", runScenario: "RUN SCENARIO", projected: "Projected fused risk", rapidDetected: "Rapid increase detected" },
  as: { regionView: "উত্তৰ-পূব অঞ্চল / কাৰ্যকৰী দৃশ্য", evolves: "পৰিৱেশৰ সৈতে বিপদ সলনি হয়। ফলাফল সলনি কৰা পৰিস্থিতিবোৰ লক্ষ্য কৰক।", offline: "অফলাইন ডেমো মোড", syncing: "সংযোগ হৈ আছে...", monitored: "নিৰীক্ষণাধীন এলেকা", activeSlope: "সক্ৰিয় ঢাল এলেকা", activeWarnings: "সক্ৰিয় সতৰ্কবাণী", pointsHour: "প্ৰতি ঘণ্টাত পইণ্ট", rapid: "পূব কৰিডৰত বিপদ দ্ৰুতগতিত বৃদ্ধি পাইছে।", routeSafety: "পথৰ সুৰক্ষা", impactPriority: "প্ৰভাৱৰ অগ্ৰাধিকাৰ", primaryReview: "প্ৰধান কৰিডৰ পৰীক্ষাধীন", easternPriority: "পূব কৰিডৰ · অগ্ৰাধিকাৰ ০১", routeCopy: "বিপদ-সচেতন পথ ব্যৱস্থাই সৰু পথ আৰু সুৰক্ষিত বিকল্প তুলনা কৰে।", impactCopy: "ব্যৱস্থা লোৱাৰ আগতে বিপদ, জনসংখ্যা আৰু আন্তঃগাঁথনি একেলগে বিবেচনা কৰক।", openRoute: "পথ বিশ্লেষণ খোলক", openImpact: "প্ৰভাৱ বিশ্লেষণ খোলক", spatial: "স্থানিক তথ্য", hazard: "লাইভ বিপদ ক্ষেত্ৰ", temporal: "সময়ভিত্তিক সংকেত", riskVelocity: "বিপদৰ গতি", conditions: "বৰ্তমান পৰিস্থিতি", rainfall: "বৰষুণ · ২৪ ঘণ্টা", currentAccumulation: "বৰ্তমান সঞ্চয়", soilMoisture: "মাটিৰ আৰ্দ্ৰতা", saturation: "পূৰ্ণতাৰ সূচক", forecastRisk: "পূৰ্বানুমান বিপদ", nextHours: "পৰৱৰ্তী ৬ ঘণ্টা", forecastWindow: "পূৰ্বানুমান সময়", peak: "০৩:৪০ ঘণ্টাত সৰ্বাধিক তীব্ৰতা আশা কৰা হৈছে", explainTitle: "এই এলেকা কিয় বিপদজনক", explainCopy: "সংযুক্ত বিপদ ইঞ্জিনে এতিয়া এই কাৰকবোৰক সৰ্বাধিক গুৰুত্ব দিছে।", activeAlerts: "সক্ৰিয় সতৰ্কবাণী", whatIf: "যদি এনেকুৱা হয় অনুকৰণ", surge: "বৰষুণৰ বৃদ্ধি পৰীক্ষা কৰক", rainfallChange: "বৰষুণৰ পৰিৱৰ্তন", runScenario: "পৰিস্থিতি চলাওক", projected: "অনুমানিত সংযুক্ত বিপদ", rapidDetected: "দ্ৰুত বৃদ্ধি ধৰা পৰিছে" },
  bn: { regionView: "উত্তর-পূর্ব অঞ্চল / কার্যকরী দৃশ্য", evolves: "পরিবেশের সঙ্গে ঝুঁকি পরিবর্তিত হয়। ফলাফল বদলে দেয় এমন পরিস্থিতি দেখুন।", offline: "অফলাইন ডেমো মোড", syncing: "সিঙ্ক হচ্ছে...", monitored: "পর্যবেক্ষিত এলাকা", activeSlope: "সক্রিয় ঢাল এলাকা", activeWarnings: "সক্রিয় সতর্কতা", pointsHour: "পয়েন্ট / ঘণ্টা", rapid: "পূর্ব করিডোরে ঝুঁকি দ্রুত বাড়ছে।", routeSafety: "পথের নিরাপত্তা", impactPriority: "প্রভাবের অগ্রাধিকার", primaryReview: "প্রধান করিডোর পর্যালোচনাধীন", easternPriority: "পূর্ব করিডোর · অগ্রাধিকার ০১", routeCopy: "ঝুঁকি-সচেতন রাউটিং সবচেয়ে ছোট পথের সঙ্গে নিরাপদ বিকল্প তুলনা করে।", impactCopy: "প্রেরণের আগে ঝুঁকি, জনসংখ্যা এবং অবকাঠামো একসঙ্গে বিবেচনা করুন।", openRoute: "পথ বিশ্লেষণ খুলুন", openImpact: "প্রভাব বিশ্লেষণ খুলুন", spatial: "স্থানিক তথ্য", hazard: "লাইভ বিপদ ক্ষেত্র", temporal: "সময় সংকেত", riskVelocity: "ঝুঁকির গতি", conditions: "বর্তমান অবস্থা", rainfall: "বৃষ্টি · ২৪ ঘণ্টা", currentAccumulation: "বর্তমান সঞ্চয়", soilMoisture: "মাটির আর্দ্রতা", saturation: "সম্পৃক্ততা সূচক", forecastRisk: "পূর্বাভাস ঝুঁকি", nextHours: "পরবর্তী ৬ ঘণ্টা", forecastWindow: "পূর্বাভাস সময়", peak: "০৩:৪০ ঘণ্টায় সর্বোচ্চ তীব্রতা আশা করা হচ্ছে", explainTitle: "এই এলাকা ঝুঁকিপূর্ণ কেন", explainCopy: "ফিউশন ইঞ্জিন এখন এই বিষয়গুলিকে সবচেয়ে বেশি গুরুত্ব দিচ্ছে।", activeAlerts: "সক্রিয় সতর্কতা", whatIf: "কী-হলে সিমুলেশন", surge: "বৃষ্টির বৃদ্ধি পরীক্ষা করুন", rainfallChange: "বৃষ্টির পরিবর্তন", runScenario: "পরিস্থিতি চালান", projected: "প্রত্যাশিত সমন্বিত ঝুঁকি", rapidDetected: "দ্রুত বৃদ্ধি শনাক্ত হয়েছে" },
  kha: { regionView: "THAIN SHATEI / KA JINGTREI", evolves: "Ka jingma ka kylla katkum ka mariang. Peit ia ki jinglong kiba pynkylla ia ka jingmih.", offline: "OFFLINE DEMO", syncing: "SYNC...", monitored: "KI THAIN BA PEIT", activeSlope: "KI THAIN SHAH", activeWarnings: "KI JINGMAHAM BA TREI", pointsHour: "POINT / KAT KA KYNTA", rapid: "Ka jingma ka kiew sted ha ka lynti mihngi.", routeSafety: "KA JINGSHNGAIN LYNTI", impactPriority: "KA JINGKTAH BA HAKHAT", primaryReview: "Ka lynti bah ka dang peit", easternPriority: "Lynti mihngi · Hakhmat 01", routeCopy: "Ka route kaba tip ia ka jingma ka pyniapher ia ka lynti lyngkot bad ka lynti shngain.", impactCopy: "Pynlang ia ka jingma, paidbah bad ki jingtei shuwa ka jingphah.", openRoute: "PYNTIAP ROUTE", openImpact: "PYNTIAP JINGKTAH", spatial: "KI TIP SHAPAT", hazard: "Ka jaka jingma live", temporal: "KA SIGNAL POR", riskVelocity: "Ka speed jingma", conditions: "Ki jinglong mynta", rainfall: "U slap · 24 kynta", currentAccumulation: "Ka jinglum mynta", soilMoisture: "Ka um ha khyndew", saturation: "Ka dak jingdap", forecastRisk: "Ka jingma shwa", nextHours: "Ki 6 kynta ban wan", forecastWindow: "KA POR SHWA", peak: "Ka bor slap kaba khraw la khmih ha 03:40 kynta", explainTitle: "Balei kane ka jaka ka long jingma", explainCopy: "Ka fusion engine ka kham bishar ia kine ki bynta mynta.", activeAlerts: "Ki jingmaham ba trei", whatIf: "WHAT-IF SIMULATION", surge: "Test ia ka jingkylla slap", rainfallChange: "Ka jingkylla slap", runScenario: "PYNIAID SCENARIO", projected: "Ka jingma ba khmih", rapidDetected: "La lap ia ka jingkiew sted" },
  brx: { regionView: "नर्थ इस्ट रिजन / अपरेसनल भ्यु", evolves: "हाबा-जोंखा गोनां जोखोम सोलायो। फोन्साफेर सोलायन हाबाफोरखौ नाय।", offline: "अफलाइन डेमो मोड", syncing: "सिंक जादों...", monitored: "मोनिटर जोंखा", activeSlope: "सक्रिय स्लोप जायगा", activeWarnings: "सक्रिय सावधान", pointsHour: "घन्टाय पइन्ट", rapid: "फोरबो रुटाव जोखोम गोबां जादों।", routeSafety: "रुट सेफ्टी", impactPriority: "इम्पेक्ट प्रायोरिटी", primaryReview: "मोजां रुट नायग्रो", easternPriority: "फोरबो रुट · प्रायोरिटी ०१", routeCopy: "जोखोम-जानाय रुटिंआ छोटो रुट आरो सेफ रुटखौ सानाय।", impactCopy: "फोन्साफोर नांगौ बेसेर जोखोम, मानसि आरो इन्फ्रास्ट्रक्चरखौ सानाय।", openRoute: "रुट बिसार खेव", openImpact: "इम्पेक्ट बिसार खेव", spatial: "जायगा बिसार", hazard: "लाइभ जोखोम जायगा", temporal: "समाय सिगनाल", riskVelocity: "जोखोम स्पिड", conditions: "दानि हाबा", rainfall: "बर्खा · २४ घन्टा", currentAccumulation: "दानि जम", soilMoisture: "हाबा हाग्रा", saturation: "हाफ्लाय सिगनाल", forecastRisk: "आगोल जोखोम", nextHours: "गुबुन ६ घन्टा", forecastWindow: "आगोल समाय", peak: "०३:४० घन्टाय गोबां बर्खा नायो", explainTitle: "बे जायगा मानो जोखोम", explainCopy: "फ्युजन इन्जिनआ दानि बे जोंखाफोरखौ गोबां हाखायो।", activeAlerts: "सक्रिय सावधान", whatIf: "हायब्ला सिमुलेसन", surge: "बर्खा सोलायन टेस्ट", rainfallChange: "बर्खा सोलायन", runScenario: "सिनारियो चालु", projected: "आगोल फ्युजन जोखोम", rapidDetected: "गोबां किव जोंखा" },
};

const renderedText: Record<string, string> = {
  "COMMAND CENTER": "commandCenter", "System ready": "systemReady", "Last sync 14:32 IST": "lastSync", "NORTH EASTERN REGION / OPERATIONAL VIEW": "regionView", "Risk evolves with the environment. Watch the conditions that change the outcome.": "evolves", "OFFLINE DEMO MODE": "offline", "SYNCING...": "syncing", "FUSED RISK": "fused", "MONITORED UNITS": "monitored", "ACTIVE SLOPE UNITS": "activeSlope", "ACTIVE WARNINGS": "activeWarnings", "RISK VELOCITY": "velocity", "POINTS / HOUR": "pointsHour", "Risk is rapidly increasing across the eastern corridor.": "rapid", "ROUTE SAFETY": "routeSafety", "IMPACT PRIORITY": "impactPriority", "Primary corridor under review": "primaryReview", "Eastern corridor · Priority 01": "easternPriority", "Risk-aware routing is ready to compare the shortest path with a safer alternative.": "routeCopy", "Combine hazard probability with population and infrastructure exposure before dispatch.": "impactCopy", "OPEN ROUTE ANALYSIS": "openRoute", "OPEN IMPACT ANALYSIS": "openImpact", "SPATIAL INTELLIGENCE": "spatial", "Live hazard field": "hazard", "TEMPORAL SIGNAL": "temporal", "Risk velocity": "riskVelocity", "ENVIRONMENTAL TRIGGERS": "conditions", "Conditions now": "conditions", "Rainfall · 24h": "rainfall", "Current accumulation": "currentAccumulation", "Soil moisture": "soilMoisture", "Saturation index": "saturation", "Forecast risk": "forecastRisk", "Next 6 hours": "nextHours", "FORECAST WINDOW": "forecastWindow", "Peak intensity expected in 03:40 hrs": "peak", "MODEL EXPLAINABILITY": "explain", "Why this area is risky": "explainTitle", "The fusion engine is weighing these factors most heavily right now.": "explainCopy", "EARLY WARNING ENGINE": "activeAlerts", "Active alerts": "activeAlerts", "WHAT-IF SIMULATION": "whatIf", "Test a rainfall surge": "surge", "rainfall change": "rainfallChange", "RUN SCENARIO": "runScenario", "Projected fused risk": "projected", "Rapid increase detected": "rapidDetected", "LANGUAGE": "language"
};

const baseText: Record<string, string> = { commandCenter: "Command console", systemReady: "System ready", lastSync: "Last sync 14:32 IST", temporal: "TEMPORAL SIGNAL", language: "LANGUAGE" };
const extraTranslations: Record<Language, Record<string, string>> = {
  en: { overview: "Overview", about: "About", dashboard: "Dashboard", launch: "Launch Console", liveLayer: "LIVE LAYER", terrain: "TERRAIN", storm: "STORM", impact: "IMPACT", openConsole: "OPEN CONSOLE", riskTicker: "RISK", ledeTerrain: "Rugged Himalayan terrain, scored cell-by-cell for long-term landslide susceptibility. Course enrollment <br>is open — models retrain weekly on new inventory data.", ledeStorm: "Monsoon rainfall and soil-moisture telemetry fused in real time. Course enrollment <br>is open — thresholds recalibrate every season.", ledeImpact: "Roads, bridges, hospitals and villages ranked by who and what a failure would strand. Course enrollment <br>is open — exposure layers refresh nightly.", commandCenter: "Command console", systemReady: "System ready", lastSync: "Last sync 14:32 IST", temporal: "TEMPORAL SIGNAL", language: "LANGUAGE" },
  as: { overview: "সাৰাংশ", about: "প্ৰকল্পৰ বিষয়ে", dashboard: "ডেশ্বব'ৰ্ড", launch: "কমান্ড কনছ'ল খোলক", liveLayer: "লাইভ স্তৰ", terrain: "ভূখণ্ড", storm: "ধুমুহা", impact: "প্ৰভাৱ", openConsole: "কনছ'ল খোলক", riskTicker: "বিপদ", ledeTerrain: "হিমালয়ৰ কঠিন ভূখণ্ডক দীৰ্ঘম্যাদী ভূমিস্খলনৰ বিপদৰ বাবে কোষে কোষে বিশ্লেষণ কৰা হৈছে। <br>নতুন তথ্যৰে মডেল সাপ্তাহিকভাৱে পুনৰ প্ৰশিক্ষণ হয়।", ledeStorm: "বৰষুণ আৰু মাটিৰ আৰ্দ্ৰতাৰ তথ্য বাস্তৱ সময়ত সংযুক্ত কৰা হৈছে। <br>প্ৰতিটো ঋতুত সীমা পুনৰ নিৰ্ধাৰণ হয়।", ledeImpact: "বিফলতাত কোন লোক আৰু কি আন্তঃগাঁথনি ক্ষতিগ্ৰস্ত হ’ব পাৰে তাৰ ভিত্তিত পথ, দলং, চিকিৎসালয় আৰু গাঁওৰ অগ্ৰাধিকাৰ নিৰ্ধাৰণ কৰা হয়। <br>প্ৰভাৱৰ স্তৰ নিশা নিশা আপডেট হয়।", commandCenter: "কমান্ড কেন্দ্ৰ", systemReady: "চিস্টেম সাজু", lastSync: "শেষ সংযোগ ১৪:৩২ IST", temporal: "সময়ভিত্তিক সংকেত", language: "ভাষা" },
  bn: { overview: "সংক্ষিপ্ত বিবরণ", about: "প্রকল্প সম্পর্কে", dashboard: "ড্যাশবোর্ড", launch: "কমান্ড কনসোল খুলুন", liveLayer: "লাইভ স্তর", terrain: "ভূখণ্ড", storm: "ঝড়", impact: "প্রভাব", openConsole: "কনসোল খুলুন", riskTicker: "ঝুঁকি", ledeTerrain: "দীর্ঘমেয়াদি ভূমিধসের ঝুঁকির জন্য হিমালয়ের কঠিন ভূখণ্ডকে কোষে কোষে বিশ্লেষণ করা হয়েছে। <br>নতুন তথ্য দিয়ে মডেল প্রতি সপ্তাহে পুনঃপ্রশিক্ষিত হয়।", ledeStorm: "বর্ষার বৃষ্টি এবং মাটির আর্দ্রতার তথ্য বাস্তব সময়ে একত্রিত হয়। <br>প্রতি ঋতুতে সীমা পুনর্নির্ধারিত হয়।", ledeImpact: "কোন মানুষ ও অবকাঠামো বিপদের কারণে আটকে যেতে পারে তার ভিত্তিতে রাস্তা, সেতু, হাসপাতাল ও গ্রামের অগ্রাধিকার নির্ধারিত হয়। <br>প্রভাব স্তর প্রতি রাতে আপডেট হয়।", commandCenter: "কমান্ড সেন্টার", systemReady: "সিস্টেম প্রস্তুত", lastSync: "শেষ সিঙ্ক ১৪:৩২ IST", temporal: "সময় সংকেত", language: "ভাষা" },
  kha: { overview: "Ka jingpynkut", about: "Shaphang ka projek", dashboard: "Dashboard", launch: "Plie ka Command Console", liveLayer: "KA LAYER LIVE", terrain: "KA RI", storm: "KA LAPP", impact: "KA JINGKTAH", openConsole: "PLIE CONSOLE", riskTicker: "JINGMA", ledeTerrain: "Ka ri Himalaya kaba eh la bishar na kawei ka cell sha kawei na ka bynta ka jingma jinglynñiar paidbah. <br>Ki model ki dang long thymmai man ka taiew.", ledeStorm: "U slap monsun bad ka um ha khyndew la pynlang ha ka por ba shisha. <br>Ki threshold ki kylla man ka aiom.", ledeImpact: "Ki lynti, jingkieng, hospital bad shnong la buh kyrteng katkum ka jingktah kaba lah ban mih. <br>Ki layer jingktah ki thymmai mynmiet.", commandCenter: "Ka Command Center", systemReady: "Ka system ka la pynkhreh", lastSync: "Sync ba khatduh 14:32 IST", temporal: "KA SIGNAL POR", language: "KA JINGIATHUH" },
  brx: { overview: "आबोहावा", about: "प्रोजेक्टनि सोमोन्दो", dashboard: "डेसबोर्ड", launch: "कमाण्ड कन्सोल खेव", liveLayer: "लाइभ लेयार", terrain: "हाजो", storm: "बर्खा", impact: "इम्पेक्ट", openConsole: "कन्सोल खेव", riskTicker: "जोखोम", ledeTerrain: "हिमालयनि रावखौ गोबां जोखोमनि थाखाय सेल-बाय-सेल बिसार जादों। <br>नावा डाटाजों मोडलआ हर हाप्ताय दानाय जादों।", ledeStorm: "बर्खा आरो हाग्रा हाबानि डाटाफोर लाइव समायाव फ्युजन जादों। <br>हर रितुआ थ्रेसहोल्ड सोलायो।", ledeImpact: "रुट, ब्रीज, हस्पिताल आरो हाबाफोरखौ मानो इम्पेक्ट जादों बेनि बादायल बिसार जादों। <br>इम्पेक्ट लेयार हर राइत अपडेट जादों।", commandCenter: "कमाण्ड सेन्टर", systemReady: "सिस्टम फोजोब", lastSync: "जोबोद सिंक १४:३२ IST", temporal: "समाय सिगनाल", language: "राव" },
};

type LanguageContextValue = { language: Language; setLanguage: (language: Language) => void; t: (key: string) => string };
const LanguageContext = createContext<LanguageContextValue | null>(null);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => (localStorage.getItem("lg-language") as Language) || "en");
  const setLanguage = (next: Language) => { setLanguageState(next); localStorage.setItem("lg-language", next); };
  useEffect(() => {
    const sourceByKey = { ...baseText, ...Object.fromEntries(Object.entries(renderedText).map(([source, key]) => [key, source])), ...Object.fromEntries(Object.entries(translations.en).map(([key, value]) => [key, value])), ...Object.fromEntries(Object.entries(dashboardTranslations.en).map(([key, value]) => [key, value])) };
    const keyBySource = new Map(Object.entries(sourceByKey).map(([key, source]) => [source, key]));
    const walk = (node: Node) => {
      if (node.nodeType === Node.TEXT_NODE) {
        const text = node.textContent ?? "";
        const trimmed = text.trim();
        const key = keyBySource.get(trimmed) ?? Object.entries(translations).flatMap(([, values]) => Object.entries(values)).find(([, value]) => value === trimmed)?.[0] ?? Object.entries(dashboardTranslations).flatMap(([, values]) => Object.entries(values)).find(([, value]) => value === trimmed)?.[0];
        if (key) {
          const translated = translations[language][key] ?? dashboardTranslations[language][key] ?? extraTranslations[language][key] ?? translations.en[key] ?? dashboardTranslations.en[key] ?? extraTranslations.en[key];
          if (translated && translated !== trimmed) node.textContent = text.replace(trimmed, translated);
        }
        return;
      }
      if (node.nodeName === "SCRIPT" || node.nodeName === "STYLE" || node.nodeName === "SELECT" || node.nodeName === "OPTION") return;
      node.childNodes.forEach(walk);
    };
    const timer = window.setTimeout(() => walk(document.body), 0);
    return () => window.clearTimeout(timer);
  }, [language]);
  return <LanguageContext.Provider value={{ language, setLanguage, t: (key) => translations[language][key] ?? dashboardTranslations[language][key] ?? extraTranslations[language][key] ?? translations.en[key] ?? dashboardTranslations.en[key] ?? extraTranslations.en[key] ?? key }}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error("useLanguage must be used inside LanguageProvider");
  return context;
}

export const languageOptions: Array<[Language, string]> = [["en", "English"], ["as", "অসমীয়া"], ["bn", "বাংলা"], ["kha", "Khasi"], ["brx", "बड़ो"]];